### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ghost** [hax0r31337/ProtoHax#18]
E  packet outbound
                                                                                                    java.lang.ExceptionInInitializerError
                                                                                                    	at dev.sora.relay.game.GameSession.onPacketOutbound(GameSession.kt:79)
                                                                                                    	at dev.sora.relay.session.MinecraftRelaySession$onPacket$1.invokeSuspend(MinecraftRelaySession.kt:57)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                                                                                    	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at java.lang.Thread.run(Thread.java:920)
                                                                                                    Caused by: java.lang.NullPointerException: MappingProvider::class.j…resourcePath/index.json") must not be null
                                                                                                    	at dev.sora.relay.game.registry.MappingProvider.<init>(MappingProvider.kt:10)
                                                                                                    	at dev.sora.relay.game.registry.ItemMapping$Provider.<init>(ItemMapping.kt:18)
                                                                                                    	at dev.sora.relay.game.registry.ItemMapping$Provider.<clinit>(Unknown Source:2)
                                                                                                    	at dev.sora.relay.game.GameSession.onPacketOutbound(GameSession.kt:79) 
                                                                                                    	at dev.sora.relay.session.MinecraftRelaySession$onPacket$1.invokeSuspend(MinecraftRelaySession.kt:57) 
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) 
                                                                                                    	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462) 
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
                                                                                                    	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
                                                                                                    	at java.lang.Thread.run(Thread.java:920) 
2023-05-27 15:23:50.151 27329-29062 AndroidRuntime          dev.sora.protohax                    E  FATAL EXCEPTION: Thread-6
                                                                                                    Process: dev.sora.protohax, PID: 27329
                                                                                                    java.lang.ExceptionInInitializerError
                                                                                                    	at dev.sora.relay.game.GameSession$onPacketOutbound$blockTask$1.invoke(GameSession.kt:72)
                                                                                                    	at dev.sora.relay.game.GameSession$onPacketOutbound$blockTask$1.invoke(GameSession.kt:71)
                                                                                                    	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
                                                                                                    Caused by: java.lang.NullPointerException: MappingProvider::class.j…resourcePath/index.json") must not be null
                                                                                                    	at dev.sora.relay.game.registry.MappingProvider.<init>(MappingProvider.kt:10)
                                                                                                    	at dev.sora.relay.game.registry.BlockMapping$Provider.<init>(BlockMapping.kt:37)
                                                                                                    	at dev.sora.relay.game.registry.BlockMapping$Provider.<clinit>(Unknown Source:2)
                                                                                                    	at dev.sora.relay.game.GameSession$onPacketOutbound$blockTask$1.invoke(GameSession.kt:72) 
                                                                                                    	at dev.sora.relay.game.GameSession$onPacketOutbound$blockTask$1.invoke(GameSession.kt:71) 
                                                                                                    	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)

**Comment by hax0r31337** [comment]
seems you are trying to build a custom ProtoHax, please follow build instructions

**Comment by ghost** [comment]
just build bleeding , when i enter server , logcat log this
