### ISSUE TITLE
?

### ISSUE THREAD

**Issue by ghost** [hax0r31337/ProtoHax#21]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
                                                                                                    	at org.cloudburstmc.netty.handler.codec.raknet.AdvancedChannelInboundHandler.channelRead(AdvancedChannelInboundHandler.java:48)
                                                                                                    	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
                                                                                                    	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
                                                                                                    	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
                                                                                                    	at org.cloudburstmc.netty.handler.codec.raknet.client.RakClientProxyRouteHandler.channelRead(RakClientProxyRouteHandler.java:50)
                                                                                                    	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
                                                                                                    	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
                                                                                                    	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
                                                                                                    	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
                                                                                                    	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
                                                                                                    	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
                                                                                                    	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
                                                                                                    	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:97)
                                                                                                    	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
                                                                                                    	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
                                                                                                    	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
                                                                                                    	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
                                                                                                    	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
                                                                                                    	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                                                                                                    	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                                                                                                    	at java.lang.Thread.run(Thread.java:920)

**Comment by ghost** [comment]
when i join in Easecation , protohax too slow and logcat error

**Comment by ghost** [comment]
serverip : ntest.easecation.net

**Comment by Wlenk** [comment]
Please wait for ProtoHax-NE(Godware) to be released.

**Comment by ghost** [comment]
not netease's easecation , bro

**Comment by oonalang** [comment]
For those who want to use they're skin i suggest to disable Ipv6

**Comment by oonalang** [comment]
For those who need help to the issue that they're facing with they're protohax dm me my name is Deleted Pleaseee make me a helper🥺

**Comment by hax0r31337** [comment]
We are not providing any help to Chinese users due to mass license violation, you can purchase our commercial branch of ProtoHax which available in China with the name of ProtoHax-NE.

由于大量违反许可证，我们不会为中国用户提供帮助，您可以购买我们的ProtoHax商业分支，该分支在中国可用的名称为ProtoHax-NE。

**Comment by oonalang** [comment]
Bro fuck you guys add aimbot or aim assist use your skills men take time and use your brains what's the use of teamcheck if it doesn't work on hive? Ik coding is hard but you guys are not one your a group dude your cheat miner doesn't even work and the fucking bhop can get you kicked and what's the point of strafe if it's not actually strafing that's called circling so many requests have been talked and called but you didn't even do any actions like the oppacity changer just for that? Like wth dude it's time to level up! Us on new generations should make difference instead of just proxy you should have two types or even three types of application the one should use proxy, the other one is just like toolbox, and the other one is a build in cheat! Dude start upgrading bruh

**Comment by oonalang** [comment]
So many clients have beat you already it's time for you to get up and beat they're clients up!

**Comment by oonalang** [comment]
It's time to take action dudes.
